### ISSUE TITLE
Let's rename our chapters to include numbers

### ISSUE THREAD

**Issue by jennybc** [aammd/UBCadv-r#7]
My usual MO is to always name something like our chapters like so:

```
01_DataStructures
02_Subsetting
03_Functions
…
```

so that when things sort lexically, they also sort (chrono)logically.

**Comment by jennybc** [comment]
@aammd @adletaw what do you think? You are the only two to have actively used the repo so far I think.

**Comment by adletaw** [comment]
Hello Jenny, it's fine with me if you add the numbers! 

On 14-07-07 07:43 PM, Jennifer (Jenny) Bryan wrote:

> @aammd https://github.com/aammd @adletaw
> https://github.com/adletaw what do you think? You are the only two
> to have actively used the repo so far I think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aammd/UBCadv-r/issues/7#issuecomment-48266224.

## 

Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast
